### ISSUE TITLE
ID value is larger than expected

### ISSUE THREAD

**Issue by 1v4r** [bitfocus/companion-module-spx-graphics-controller#2]
The Companion button form expects a value between 0 and 20. The action still works.
SPX-GC item IDs are much larger (i.e 1628506602446)
![bilde](https://user-images.githubusercontent.com/15363880/130333604-21da26d5-6778-41a7-90e4-34980f5a8159.png)

**Comment by JeffreyDavidsz** [comment]
I've changed this to text, as I understood text values are allowed also
