### ISSUE TITLE
Port number is static

### ISSUE THREAD

**Issue by 1v4r** [bitfocus/companion-module-spx-graphics-controller#3]
The network port number is hard coded in the module to the default port 5000.
In SPX-GC the port number can be changed.
Please add option to change the port number in the module as well.

![bilde](https://user-images.githubusercontent.com/15363880/130355216-6120b61b-a376-41b2-8506-8727cdba69c9.png)

![bilde](https://user-images.githubusercontent.com/15363880/130355241-91916491-4efe-4059-bacf-c76bdf883122.png)

**Comment by JeffreyDavidsz** [comment]
done in the latest build
