### ISSUE TITLE
Item ID can be alphanumeric

### ISSUE THREAD

**Issue by wde** [bitfocus/companion-module-spx-graphics-controller#4]
Hi there, 

What a brilliant addition! Thanks @JeffreyDavidsz 

We have been interfacing using the generic http connector. We have a script that modifies each SPX-GC playout file directly from a broadcast run-sheet in another system and have been using IDs such as "news" and "logo" instead of a number.

I can change back to a numeric ID but it would be great to be able to enter alphanumeric characters in the field too.

I will also have a chat with Tuomo about the possibility of adding in some feedback from the API which would be pretty cool too.

Thanks again for your work on this - I'm a fan.

Cheers,
Sean

**Comment by JeffreyDavidsz** [comment]
I wasn't aware it could be text also, I've changed it to a textfield allowing for text
