### ISSUE TITLE
Rename request

### ISSUE THREAD

**Issue by TuomoKu** [bitfocus/companion-module-spx-graphics-controller#5]
Hi, thank you for adding the SPX-GC module to Companion.

The app is right now going through a rename process and "SPX-GC" will in the future be called simply "SPX". Can you please rename the module to reflect this? 

Thank you!

**Comment by Julusian** [comment]
We prefer to follow the naming scheme of `company-product`, which `spx` wouldn't conform to.
You are referring to the application as `SPX Graphics Controller` at points, so would you be ok with the longer name `spx-graphics-controller`?

**Comment by TuomoKu** [comment]
Hi,

Yes that is absolutely correct. We will start to use that name to
distinguish between the app from the overall SPX ecosystem.

So yes, that fits us perfectly.

Thank you!

-Tuomo

pe 24. marrask. 2023 klo 22.47 Julian Waller ***@***.***>
kirjoitti:
