### ISSUE TITLE
SPX-GC is an overlay manager

### ISSUE THREAD

**Issue by wde** [bitfocus/companion-module-spx-graphics-controller#6]
Hi there,

I have been using SPX-CG to manage broadcast overlays via a web interface. It allows the creation of dynamic templates using HTML & javascript. I have also been able to take a +20Mb video created in After Effects and using Lottie Files to convert it to a 600kb JSON file and added to a template.

It would be great to be able to link a playout to Companion and assign each asset to a button for easy access.

What do you think?

Github: https://github.com/TuomoKu/SPX-GC 

From: https://smartpx.fi/gc/ 

> Dynamic multi-layer graphics for professional quality live video production and streaming.
> 
> SPX-GC (or "GC" for short) is a graphics controller for professional live television broadcasts and web streams using HTML graphics on CasparCG and/or streaming software such as OBS, Wirecast, XSplit or vMix.
> 
> - Lower thirds, logos, bumpers, tickers, titles, lyrics, scripture, countdowns...
> - Linked layers can affect other's positioning on-screen
> - External data sources (such as spreadsheets, social reactions, feeds, etc)
> - Unlimited projects, templates and rundowns
> - Utilize existing HTML templates
> - On-premise installation Windows, Mac, Linux
> - Cloud instances for remote workflows
> - Operator friendly user interface
> - GC comes with production-ready example templates with customizable colours and fonts.
> 
> SPX-GC is free, open-source software.

Cheers,
Sean

**Comment by thomahawk72** [comment]
Hi, I am really looking forward to this being part of Companion. What's the timeline on that?

**Comment by josephdadams** [comment]
I believe it is in the 2.2 betas
